---
title: "Public Health Data Analysis"
author: "Lekshmi Rita Venugopal"
date: "`r Sys.Date()`"
output: learnr::tutorial
runtime: shiny_prerendered
---

```{r setup, include=FALSE}
library(learnr)
knitr::opts_chunk$set(echo = FALSE)
```


## Lesson: EWMA Calculation and Control Chart

Welcome to the lesson on calculating Exponentially Weighted Moving Average (EWMA) and creating a control chart using R!

### Load necessary libraries


```{r load_library, exercise = TRUE}
library(dplyr)
library(qcc)
library(ggplot2)
library(readxl)

```

### Create the simulation data with the columns `Date` and `Incidence_rate`

```{r create-data, exercise = TRUE}
simulation <- data.frame(
  Date = seq(as.Date("2024-01-01"), as.Date("2024-04-09"), by="day"),
  Incidence_rate = c(6.253319, 8.971453, 5.95713, 11.368602, 10.774229, 5.516471, 5.451247, 10.584614,
                     7.123854, 7.215942, 11.379639, 6.497677, 7.666793, 5.981425, 2.928209, 10.303529,
                     5.44821, 4.053004, 6.922267, 13.050085, 9.508969, 5.690831, 9.005739, 12.290799,
                     7.311991, 9.025571, 6.715227, 5.779282, 6.181303, 4.861109, 11.005764, 10.38528,
                     7.62934, 9.644377, 2.779513, 7.331782, 9.096839, 5.435181, 5.674068, 6.148808,
                     5.993504, 6.548397, 6.238732, 5.372094, 6.360652, 4.39974, 7.187333, 8.532611,
                     5.7643, 7.973579, 3.289593, 7.256884, 8.753308, 3.652457, 6.048381, 4.954972,
                     4.215096, 6.332058, 9.619773, 16.918997, 17.424653, 14.607964, 14.382117, 15.944438,
                     19.519407, 17.301153, 19.105676, 18.359294, 18.150296, 14.975871, 8.117647, 7.052525,
                     7.509443, 1.743908, 8.843862, 4.34805, 6.235387, 7.077961, 5.038143, 3.928692,
                     6.444551, 8.451504, 6.041233, 8.577503, 1.946753, 7.131337, 10.53936, 10.739948,
                     11.909104, 3.556107, 5.701784, 7.737803, 4.427856, 6.485332, 4.398464, 4.469093,
                     7.538244, 4.687917, 9.100109, 5.71297)
)

```

```{r view-data, exercise = TRUE}
head (simulation)
```

### Check for any missing values in the dataset
```{r missing_data, exercise = TRUE}
sum(is.na(simulation))
```


### Calculate EWMA

```{r EWMA, exercise = TRUE}
alpha <- 0.3
initial_value <- simulation$Incidence_rate[1]
simulation <- simulation %>% mutate(ewma = ifelse(row_number() == 1, initial_value, NA))

for (i in 2:nrow(simulation)) {
  simulation$ewma[i] <- alpha * simulation$Incidence_rate[i] + (1 - alpha) * simulation$ewma[i - 1]
}
```


### Create control chart
```{r control_chart, exercise = TRUE}
control_chart <- qcc(simulation$ewma, type = "xbar.one", title = "EWMA Control Chart", xlab = "", ylab = "value")

ewma_center <- control_chart$center
sd <- control_chart$std.dev
ewma_lcl <- control_chart$limits[, "LCL"]
ewma_ucl <- control_chart$limits[, "UCL"]
```

### Plot EWMA
```{r plot, exercise = TRUE}
# Create a column to indicate if the data point is above the UCL
simulation <- simulation %>%
  mutate(Out_of_control = ewma > ewma_ucl)

# Plot the EWMA control chart
ggplot(simulation, aes(x = Date, y = ewma)) +
  geom_line() +
  geom_ribbon(aes(ymin = ewma_ucl, ymax = ewma_ucl), fill = "grey", alpha = 0.3) +
  geom_point(aes(color = out_of_control), size = 1) +
  geom_hline(yintercept = ewma_ucl, linetype = "dashed", color = "black") +
  geom_hline(yintercept = ewma_center, linetype = "dashed", color = "black") +
  labs(title = "EWMA Control Chart", x = "Date", y = "EWMA") +
  scale_color_manual(values = c("black", "red"), labels = c("Below UCL", "Above UCL")) +
  theme_minimal()

```






